DROP DATABASE IF EXISTS rpg;
CREATE DATABASE rpg;
USE rpg;


CREATE TABLE IF NOT EXISTS characters (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  class VARCHAR(50) NOT NULL,
  weapon VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS powers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL,
  damage INT NOT NULL,
  character_id INT,
  FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE
);

SHOW TABLES;
DESCRIBE powers;
DESCRIBE characters;